### ISSUE TITLE
uploadに対してvalidiationを追加してほしい

### ISSUE THREAD

**Issue by Hosi121** [Hosi121/ShareTube#47]
### As Is

タグがかなり長い文字数入力できてしまう．
説明欄に文字数制限がない．
タグの数は協議すべきだけど，5つぐらいでよい気がする．

![image](https://github.com/user-attachments/assets/4f18999d-300f-469d-bd42-f022b21c7406)

### To Be

-[ ] 入力の制約を付ける

### working branch

fix/frontend/upload-validation

**Comment by araaki12345** [comment]
PR #50 にて修正
